### ISSUE TITLE
Morpho Device not working with Android Version 5+

### ISSUE THREAD

**Issue by ankitsrivastava108** [khosla-labs/aadhaar-bridge#1]
The bridge APK is not working for Android version 5+ with Morpho Finger print device.

**Comment by smutneja03** [comment]
The Morpho SDK used in the bridge APK does not support Android 5. 
We are working on the upgrade.

**Comment by brijeshmasrani** [comment]
Hi @smutneja03, Any update on this. We are unable to use BioMetric feature.

**Comment by guneshpatil** [comment]
Hi @smutneja03, any update on Support for Android 5? I am unable to use Morpho device that you sent in developer kit. I need this testing done so that we can go ahead for production server deployment package with Aadhaar Bridge. It is holding up things.

Please provide an update.

**Comment by jaydeep1993** [comment]
Morpho device for Android 5.+ is added. Please download latest AadhaarBridge_2.1.apk .
