### ISSUE TITLE
Issues while moving from Developer edition to Enterprise edition

### ISSUE THREAD

**Issue by tanuka72** [khosla-labs/aadhaar-bridge#10]
I had tested the Developer edition of Aadhaar Bridge (for authentication) two months ago. I've now purchased the Enterprise edition using a new account but am unable to perform Aadhaar authentication because of two issues (possibly related). I have sent email about these issues to your customer support alias but haven't received a response.

1. On my Android app, when I try to initiate Aadhaar authentication using demographics (Name + Aadhaar number - both valid), I get the error "Enter a valid Aadhaar number" from AadhaarBridge.apk

This error started appearing from the day my developer edition expired, so I suspect that some flag has been set on the phone. Even though I've uninstalled and reinstalled AadhaarBridge.apk, executed Clear Cache and Clear Data through the Android Application manager, I still get this error when trying to perform authentication.

2. On the portal, I am unable to whitelist my server IP address (where the gateway is running) because this IP address exists on your system with my earlier developer edition account. I am unable to access the Manage IP menu on your portal with my developer edition credentials, so please could you delete this at the back-end, so that I can associate my new account with this IP address. I cannot change my server IP address - that is not an option.

Regards,
Tanuka

**Comment by smutneja26** [comment]
The Aadhaar Bridge Team has now replied back on the mail. 

1. The IP whitelisting part has been taken care of. You can now add the IP you want to whitelist in your new account settings. 

2. You can refer the app present here https://github.com/khosla-labs/aadhaar-bridge/tree/master/examples and https://github.com/khosla-labs/aadhaar-bridge/blob/master/libraries/AadhaarBridge.apk for checking the system. There is no flag that gets set on account expiry. Even after the account is expired, you can still make request but it will be the service that will not allow it to go further i.e. client level check is not present.
