### ISSUE TITLE
kyc/raw  - K 100 and  K 543

### ISSUE THREAD

**Issue by manansbeg** [khosla-labs/aadhaar-bridge#11]
Hi ,

We are sending the following request to aadhaar bridge using postman:
     {
        "consent": "Y",
        "auth-capture-request": {
            "aadhaar-id": "695608629805",
            "location": {
                "type": "pincode",
                "pincode": "190008"
            },
             "modality": "otp",
            "certificate-type": "prod",
            "otp":"108285"
        }
    }
We are getting K-100  as the reply.
The same call give K 543 from android SDK

The OTP service works fine.

**Comment by smutneja03** [comment]
The OTP you have received can be used only once. Successive use of the same OTP will give you an error. 

In the android, as mentioned in the link here https://developer.uidai.gov.in/site/book/export/html/41, make sure the time is set to IST in the device settings. Once done, the service should work fine.

**Comment by manansbeg** [comment]
Hi Sahil , we generate the OTP each time

**Comment by manansbeg** [comment]
Here are the exact steps I did just now:

1. On 119.18.52.254:8181/otp
Json request body:   {
        "aadhaar-id": "695608629805",
        "device-id": "ad124",
        "certificate-type": "prod",
        "channel":"SMS",
        "location": {
            "type": "pincode"
         
            "pincode": "190008"
        }
    }

Response: {"success":true,"aadhaar-reference-code":"ab82c4b20dbe4239a455cb61d60e1903"}
2. I got the OTP on my mobile . Lets say its 123456
3. On 119.18.52.254:8181/kyc/raw
Body:
     {
        "consent": "Y",
        "auth-capture-request": {
            "aadhaar-id": "695608629805",
            "location": {
                "type": "pincode",
                "pincode": "190008"
            },
             "modality": "otp",
            "certificate-type": "prod",
            "otp":"123456"
        }
    }

We got response: 
{"aadhaar-id":"695608629805","success":false,"aadhaar-status-code":"K-100","aadhaar-reference-code":"d0a2a32d34514605b235a5c45306d2ea"}

**Comment by smutneja03** [comment]
On checking the system, services seems to be running fine. Make sure the application is sending the proper request for each generated OTP. 

In the JSON, kindly change the certificate-type to preprod and things should work fine. 
        
    "certificate-type": "preprod"

**Comment by brijeshmasrani** [comment]
Yes from Android it's 							
AuthCaptureRequest authCaptureRequest = new AuthCaptureRequest();
authCaptureRequest.setCertificateType(CertificateType.preprod);

**Comment by manansbeg** [comment]
Thanks for the quick investigation:

Now , I am getting {"aadhaar-id":"695608629805","success":false,"aadhaar-status-code":"K-543","aadhaar-reference-code":"a767dc0e25604334ac0dfe1603768018"}

**Comment by smutneja03** [comment]
For K-543, set the time settings in your device to IST and then try hitting the service.

**Comment by manansbeg** [comment]
Both the webclient (POSTMAN) and android are stuck at the same issue. Though this is progress from yesterday :)

**Comment by manansbeg** [comment]
The new kyc req ;

     {
        "consent": "Y",
        "auth-capture-request": {
            "aadhaar-id": "695608629805",
            "location": {
                "type": "pincode",
                "pincode": "190008"
            },
             "modality": "otp",
            "certificate-type": "preprod",
            "otp":"123456"
        }
    }

**Comment by smutneja03** [comment]
Are you setting the OTP value you are receiving from the OTP service in the request you are sending for KYC. And did you check after changing the time setting in your android device ?

**Comment by manansbeg** [comment]
Android device - Yes,
Setiing OTP - Yes

**Comment by manansbeg** [comment]
What exactly is this pincode? Is this the pincode of registered address?

**Comment by brijeshmasrani** [comment]
Android Setting :- [http://imageshack.com/a/img924/7480/c5KlyN.png]

**Comment by smutneja03** [comment]
Pincode basically should point to the place from where the request is getting generated and eventually sent i.e. the location of the server on which Aadhaar Bridge provided gateway jar is running.

**Comment by manansbeg** [comment]
For android, what do you think is the problem? The screenshot clearly shows that time zone is IST,

**Comment by smutneja03** [comment]
Have you changed the certificate type to preprod. In the JSON you have mentioned, its still prod which is specified.

**Comment by manansbeg** [comment]
its prepod now

**Comment by smutneja03** [comment]
Is the POSTMAN client working for you now ?

**Comment by manansbeg** [comment]
no, its not

**Comment by manansbeg** [comment]
I am checking my server location. Is it really important to have the correct pincode for server?

**Comment by smutneja03** [comment]
Some valid value needs to be mentioned. Validations based on it are not done at the UIDAI end.

**Comment by manansbeg** [comment]
{"aadhaar-id":"695608629805","success":false,"aadhaar-status-code":"K-100","aadhaar-reference-code":"0523056ea5c84ab89f5b4e9031f35cd3"}

**Comment by manansbeg** [comment]
When I changed my pincode

**Comment by manansbeg** [comment]
OTP
{
        "aadhaar-id": "695608629805",
        "device-id": "ad124",
        "certificate-type": "preprod",
        "channel":"SMS",
        "location": {
            "type": "pincode",
         
            "pincode": "574195"
        }
    }


{"success":true,"aadhaar-reference-code":"d4d13919985b42a4933bbec216b28ffb"}

/kyc/raw

     {
        "consent": "Y",
        "auth-capture-request": {
            "aadhaar-id": "695608629805",
            "location": {
                "type": "pincode",
                "pincode": "574195"
            },
            "modality": "otp",
            "certificate-type": "preprod",
            "otp":"613040"
        }
    }

**Comment by smutneja03** [comment]
On further inspection of the response from the UIDAI, the error that you are getting is 584 which is due to an invalid pincode. 

        If pincode value is not one of the valid values in UIDAI system, this error occurs

Kindly mention some other value in the pincode field and try sending the request again. for eg : 560067

**Comment by manansbeg** [comment]
Now stuck at 543
     {
        "consent": "Y",
        "auth-capture-request": {
            "aadhaar-id": "695608629805",
            "location": {
                "type": "pincode",
                "pincode": "560067"
            },
            "modality": "otp",
            "certificate-type": "preprod",
            "otp":"826993"
        }
    }
Response:
{"aadhaar-id":"695608629805","success":false,"aadhaar-status-code":"K-543","aadhaar-reference-code":"34dd9cbf7a9546d4b5662c0572bbd5fd"}

**Comment by manansbeg** [comment]
Is it possible I need to change some time setting on server?
We are stuck at K-543 - Invalid timestamp (“ts” attribute in “Kyc” element)

**Comment by manansbeg** [comment]
KYC is working fine. I changed the timezone to IST for the http server too. 
Thanks for all the help Sahil .

**Comment by smutneja03** [comment]
no problem :+1:

**Comment by brijeshmasrani** [comment]
@smutneja03  Thank You for the support.

**Comment by shri20** [comment]
Hello @manansbeg Can you tell how did you changed changed the timezone to IST for the http server.

**Comment by abhas9** [comment]
@shri20 for ubuntu box try `sudo dpkg-reconfigure tzdata`
