### ISSUE TITLE
OTP not coming on mobile

### ISSUE THREAD

**Issue by manansbeg** [khosla-labs/aadhaar-bridge#12]
Hi,

We are seeing erratic behaviour in generation of otp.
We are getting a response {"success":true,"aadhaar-reference-code":"5b48564bde3540e7b44c85aa46c5a07e"} on calling the OTP webservice but no OTP is being generated.

Out of multiple attempts made, OTP came on the mobile only once. 
This was working properly in the morning.

Thanks
Manan

**Comment by smutneja03** [comment]
The Work of Aadhaar Bridge is to provide a platform wherein a user can send a request and for each valid request gets back a proper response from the UIDAI.

In the case you have mentioned, you are getting a proper response from the UIDAI. The OTP that you get is managed by their team and not by Aadhaar Bridge, so it will be tough to comment as to why this is happening. 

As checked and tested locally, things are working fine now. In case it again happens in future, try hitting the service after some time and if it still doesn't work, feel free to write to us and we will follow up with the UIDAI on the same.

**Comment by manansbeg** [comment]
Hi Sahil,

Its working fine now. I think for 2-3 hours it was not working properly.

Thanks
Manan
