### ISSUE TITLE
i need to develop adhar-bridge windows authentication through .net

### ISSUE THREAD

**Issue by naveenswithu12** [khosla-labs/aadhaar-bridge#13]
i need to develop adhar-bridge windows authentication through .net any dotnet libraries dll available

**Comment by naveenswithu12** [comment]
Hi

plz let me know any dlls available for .net to implement Adhar bridge web application

**Comment by naveenswithu12** [comment]
Hi

Aadhaar Authentication in Asp.net any dlls available

**Comment by smutneja03** [comment]
There are no dlls that aadhaar bridge currently provides. The only platform that AB currently supports is Java based. The requirement of such a system is there only if a person wants to do pid encryption within the application itself. Rest assured, the same thing can be done via just sending plain JSON(independent of the user application) to the gateway provided by Aadhaar Bridge. 

For your case, you can send the JSON request to the gateway exposed API's through your .net application and you will be good to go for demographic authentication, otp based authentication and otp based kyc.
