### ISSUE TITLE
Extension of demo account for two weeks

### ISSUE THREAD

**Issue by corportewebtech** [khosla-labs/aadhaar-bridge#14]
Hi,

We need urgent extension of our demo account for two weeks, kindly do the extension as soon as possible.

Accoun username is info@corporatewebtechnologies.com

Thanks
Umesh
9818439700

**Comment by saranya-gopinath** [comment]
Hi Umesh,

Unfortunately we do not provide extensions of our Developer Account. For continued unhindered access,  you may consider signing up for the enterprise edition.
