### ISSUE TITLE
KYC Check using Non Biometric Authentication is returning False Result inspite of correct data.

### ISSUE THREAD

**Issue by tdesai79** [khosla-labs/aadhaar-bridge#15]
Hi,
We are trying to do KYC check based on Non Biometric OTP based KYC Check. 
We have gone through the following link 
https://github.com/khosla-labs/aadhaar-bridge/wiki/JSON%20Based%20Request

Steps we followed and result obtained are as follows

Step1 : Generate OTP;
url :           http://103.247.149.33:8181/otp 
Json sent: {
        "aadhaar-id": "993801548048",
        "device-id": "",
        "certificate-type": "preprod",
        "channel":"SMS",
        "location": {
            "type": "",
            "latitude": "",
            "longitude": "",
            "altitude": "",
            "pincode": ""
        }
    }

Result: {"success":true,"aadhaar-reference-code":"a73aaa08d38c4bccae2368b1ade952be"}

Then we received sms for OTP from addhar on the registered mobile no which we passed to next call as followed

Step2 : KYC JSON request;
url :           http://103.247.149.33:8181/kyc/raw
Json sent: {
        "consent": "Y",
        "auth-capture-request": {
            "aadhaar-id": "993801548048",
            "location": {
                "type": "pincode",
                "pincode": "411037"
            },
            "modality": "otp",
            "certificate-type": "preprod",
            "otp":"377181"
        }
}

Result:{"success":false,"aadhaar-status-code":"500"}

Please let us know are we doing the right step or something else to be done. We were expecting Users Information like address etc in return. Let us know if this is the right method.

**Comment by smutneja03** [comment]
Kindly specify the saCode associated with your account. Refer the link to know it https://bridge.aadhaarconnect.com/portal/sauser.app.html#/profile-view

**Comment by tdesai79** [comment]
Hi, 
thanks for quick reply. the saCode associated with our account is as follows
Sub AUA Code : DKbf33ec
is this the same what you are asking?

**Comment by tdesai79** [comment]
Hello Sahil,
Sub AUA Code DKbf33ec

Hope this helps.

*Thanks and Regards,*

*Tushar Desai*
Director IT Solutions
Emmersive Infotech, Pune
Cell: +91 9689899969
www.emmersivetech.com

**Comment by smutneja03** [comment]
The account doesn't have e-KYC included in it. Its only Auth enabled(Rs. 5000/- + taxes) due to which you are not able to access the e-KYC service.

**Comment by tdesai79** [comment]
Hi, we are trying to implement kyc/raw in android app using fingerprint. while going through following link  https://github.com/khosla-labs/aadhaar-bridge/wiki/Supporting-Libraries-and-Services.
we came across supported devices.( Digital Persona ,Mantratec ,Iritech ,Safran Morphosmart MSO 1300). Does it mean that we can not implement fingerprint verification on normal android device which has inbuilt fingerprint recognition sensors? or in other words we can connect only the above listed/supported devices externally to android device?

**Comment by pasathiskumar** [comment]
Please help me my sub aua code is e9b11c
{"success":false,"aadhaar-status-code":"500"} what's the issue? plz

**Comment by nikleshjain** [comment]
Hi,
We are trying to do KYC check based on Non Biometric KYC Check.
We have gone through the following link
https://github.com/khosla-labs/aadhaar-bridge/wiki/JSON%20Based%20Request

KYC JSON Request :

i make changes in application.propertise with certficates path and subaua code and after that using command (java -jar aadhaarbridge-kua-gate-0.0.1-SNAPSHOT.jar) just showing c.a.bridge.gate.Application --> started application 

var jsonObjects = {"consent": "Y","auth-capture-request": {"aadhaar-id": "993801548048","location": {"type": "pincode","pincode": "560067"},"modality": "otp","certificate-type": "preprod","otp":"377181"}};
		$.ajax({
			type: "POST",
			dataType: 'application/json',
			url: "http://206.19.38.1:8181/kyc/raw",    -----     Default Gateway IP
			data: {params: JSON.stringify(jsonObjects) },
			success: function (result) {
				alert(result);
			}
		});

Result: Not giving any result

Please let us know are we doing the right step or something else to be done.

**Comment by pasathiskumar** [comment]
did yu get otp ?http://103.247.149.33:8181/otp
are yu  finsihed first step?

**Comment by nikleshjain** [comment]
My gateway ip also not working for OTP. can we go with localhost

Please let us know are we doing the right step or something else to be done.

**Comment by pasathiskumar** [comment]
can you share your application.properties file 
pasathiskumar@gmail.com

**Comment by shri20** [comment]
Hello @tdesai79, Did you find solution for this.


Thanks & Regards,
Shriram

**Comment by dhanushkumarv** [comment]
Hello I am dhanush,
![default p12 error](https://user-images.githubusercontent.com/9839734/27670598-8a2b3b1e-5cab-11e7-914e-652d0f75cc19.JPG)

While running the json values i am getting .P12 file not found error.
can anyone suggest me how to fix this error.
Please find the screenshot

**Comment by dhanushkumarv** [comment]
hello i am dhanush,
did any one find the solution for above error?

**Comment by jaydeep1993** [comment]
@dhanushkumarv It clearly says File not found Exception. Make sure you specified correct path to your .p12 file in application.properties file

**Comment by dhanushkumarv** [comment]
@jaydeep1993 thanks for your reply
i checked it still same issues

**Comment by dhanushkumarv** [comment]
i am using ubuntu 14.04 server
.p12 file is located in /usr/cert/.p12
in application properties mentioned /usr/cert/.p12
and another certificate location also same path /usr/cert/82194e.cer

STILL GETTING SAME ERROR

**Comment by dhanushkumarv** [comment]
file not found exception error came

**Comment by jaydeep1993** [comment]
Check if you .p12 file has appropriate permission so that gateway jar file can access it.

**Comment by jaydeep1993** [comment]
Please drop your query at tech.support@aadhaarbridge.com .
