### ISSUE TITLE
AadhaarBridge.apk crashes on Android 5.1.1 when connecting to Digital Persona fingerprint scanner

### ISSUE THREAD

**Issue by tanuka72** [khosla-labs/aadhaar-bridge#2]
On a phone running Android 5.1.1, using AadhaarBridge.apk to connect to the Digital Persona EikonTouch fingerprint scanner causes the application to crash. This does not happen on Android 5.0.2.

**Comment by smutneja03** [comment]
We tried reproducing the issue on Android 5.1.1 using Digital Persona eikonTOUCH fingerprint scanner but failed. Our [sample app](https://github.com/khosla-labs/aadhaar-bridge/tree/master/examples/AadhaarBridgeSamplerApp) works successfully with the specified device and Android version. 

Try using our sample app to confirm the issue at your end.
