### ISSUE TITLE
Pre Production Environment

### ISSUE THREAD

**Issue by better-place** [khosla-labs/aadhaar-bridge#20]
Hi Team,

I am not able to authenticate aadhaar in pre-production environment. It's always giving 500 error. Please check this issue

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
