### ISSUE TITLE
Unable to access the local Aaadhaar brdige gateway

### ISSUE THREAD

**Issue by PavanBilagi** [khosla-labs/aadhaar-bridge#21]
Unable to frame the service URL and input request JSON to consume the Aadhaar gateway service in the pre-production URL

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
