### ISSUE TITLE
Couldn't Generate OTP using Json based request 

### ISSUE THREAD

**Issue by karthikeyan-jothi** [khosla-labs/aadhaar-bridge#22]
We are trying to generate OTP using the below json format to the gateway server 
 {
        "aadhaar-id": "645446389945",
        "device-id": "",
        "certificate-type": "preprod",
        "channel":"SMS",
        "location": {
            "type": "",
            "latitude": "",
            "longitude": "",
            "altitude": "",
            "pincode": ""
        }
    }

But the response comes as 
{"success":false,"aadhaar-status-code":"111","aadhaar-reference-code":"4c1d7e83c7ec46a1a5af45acc4618363"}

kindly let me know if the json format is wrong and what does that status code means and i couldn't find this status code in UIDAI API error code's.

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
