### ISSUE TITLE
Morpho device not working with Android 5.1

### ISSUE THREAD

**Issue by nik86vaidya** [khosla-labs/aadhaar-bridge#23]
Hi,

Android Bridge APK crashes while doing fingerprint scanning using Morpho device. I am using MotoG 1st Gen with Android 5.1 version. 

Device details:
Name: Morpho device
Model: MSO1300 E

Could you please look into this issue?

Note: Someone has already raised issue for the same long back but could not see any resolution.
https://github.com/khosla-labs/aadhaar-bridge/issues/1

**Comment by SujeetKr9** [comment]
i thik sample app not supported in android 5 or 5+....

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
