### ISSUE TITLE
Incrorrect response for DOB using correct Aadhaar number and DOB when the request is encrypted

### ISSUE THREAD

**Issue by nik86vaidya** [khosla-labs/aadhaar-bridge#24]
Hi,

Incrorrect response for DOB using correct Aadhaar number and DOB when the request is encrypted.

For encryption we are using below statement:
AadhaarBridgeUtil.buildAuthRequest(authCaptureRequest);

which is a part of libraries available on Aadhaar bridge protal.

I mail the encrypted request JSON at below email id: 
tech.support@aadhaarbridge.com
with 
Subject: Incrorrect response for DOB using correct Aadhaar number and DOB when the request is encrypted

Please have a look and let us know the root cause.

Note: We are getting correct response for the same record using "auth/raw" API (without encryption)

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
