### ISSUE TITLE
Aadhaar bridge sample apk not opening

### ISSUE THREAD

**Issue by aes009** [khosla-labs/aadhaar-bridge#26]
I have installed Aadhaar bridge sample apk,but after installation there is no icon showing of this app in my phone.how can i open this app

**Comment by aes009** [comment]
please reply

**Comment by rohitshukla92** [comment]
Hi,
The apk which you have installed is aadhaarbridge.apk and has no launcher activity. There is one more apk install it too. The name of that APK is AadhaarBridgeSampler application.

**Comment by aes009** [comment]
how can i get this app,I am not able to find it

**Comment by aes009** [comment]
please reply

**Comment by mjain01** [comment]
There is no AadhaarBridgeSampler apk.

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).

**Comment by mjain01** [comment]
Sample on github not working.
Not showing output
