### ISSUE TITLE
AUA Status code 500

### ISSUE THREAD

**Issue by better-place** [khosla-labs/aadhaar-bridge#27]
Hi Team,

We are getting AUA Status from Aadhaar Bridge system since last night. We are trying to do aadhaar authentication. Please look into this on priority because our whole aadhaar verification process stopped.

Thanks,
Pulkit Gupta

**Comment by Junotele** [comment]
Hi Team,
Any update on the same issue,we are also facing same issue while verification of aadhaar.

Thanks,
T.Srinivasu

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
