### ISSUE TITLE
Building OTP Data for OTP Verification code not including otp

### ISSUE THREAD

**Issue by sandeep-venugopal** [khosla-labs/aadhaar-bridge#28]
We have an Andriod App  and we need to do non-biometric KYC and hence using this code

`AuthCaptureRequest authCaptureRequest = new AuthCaptureRequest();
authCaptureRequest.setModality(Modality.otp);
authCaptureRequest.setOtp(otp);
authCaptureRequest.setAadhaar(aadhaarID);
authCaptureData = AadhaarBridgeUtil.buildAuthRequest(authCaptureRequest);
String json = new Gson().toJson(authCaptureData);

KycCaptureData kycCaptureData = new KycCaptureData();
kycCaptureData.setConsent(ConsentType.Y);
kycCaptureData.setAuthCaptureData(authCaptureData); //refer authCaptureData for otp verifier
kycCaptureData.setTs(ISO8601.now());
String json = new Gson().toJson(kycCaptureData);
`

But this code is not inserting otp data even though I'm setting otp in the request payload

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
