### ISSUE TITLE
Unable to generate OTP

### ISSUE THREAD

**Issue by Dipkatts** [khosla-labs/aadhaar-bridge#29]
We are using JSON based request from php curl. It is hitting the gateway. But error code is 

string(237) "{"timestamp":1478696181376,"status":500,"error":"Internal Server Error","exception":"com.google.gson.JsonSyntaxException","message":"java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1","path":"/otp"}"

We are not getting any help to solve this one.

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
