### ISSUE TITLE
Certificate Type: Staging

### ISSUE THREAD

**Issue by nik86vaidya** [khosla-labs/aadhaar-bridge#3]
I am integrating Aadhaar bridge APIs with our product. I have few queries regarding the use cases of APIs:

1) There is a class called AuthCaptureRequest to create request. It contains a method called setCertificateType() and the valid values for the same are preprod, prod and staging.

Can I get some document for CetificateType "Staging"? I couldn't find the use case of Staging certificate type anywhere in the document.

2) In the UIDAI API documents it is mentioned that APIs provide support for Phonetic Matching. To use phonetic matching feature developer has to use below methods:
      a) lname : to set language
      b) lmv: to set matching percentage
But while actual implementing it I found that class doesn't contains these 2 methods.

Can anyone help me out in above 2 queries?

Thanks
Nikhil Vaidya

**Comment by smutneja03** [comment]
Staging environment is purely for testing purpose which anyone can use without passing through Aadhaar Bridge or in general AUA. Instructions for the same are present [here](https://www.developer.uidai.gov.in/site/node/21)

The point to note out here is, the data you can test against is not real. It's fabricated data which is meant only for testing. One can also add their aadhaar details by filling out this [form](https://docs.google.com/forms/d/14Kn6rvY8awAnAX3sgt0F1MK5s0dgTpnPQKigH6DaS3M/viewform?formkey=dDJMZ3lWeTNNRE1ReVJUX1pURXZSNmc6MQ&fromEmail=true) as also mentioned in the link

**Comment by nik86vaidya** [comment]
Thanks for reply. I will look into the link mentioned above.

Could you please help us in resolving the blocker issue which I had mailed to earlier?

**Comment by pranjal-goswami** [comment]
Closing this issue for staging Cert. Please open a new issue for any other queries.
