### ISSUE TITLE
[aadhaarbridge-kua-gate] SSL/TLS handshake failure on jre/jdk 8+

### ISSUE THREAD

**Issue by rajesh-rangde** [khosla-labs/aadhaar-bridge#30]
The bundled Bouncy Castle library (bcprov-jdk16) has issues establishing TLS connections on jdk8.
The TLS connection (to https://bridgetest.aadhaarconnect.com/) fails to establish.

Stacktrace:

> Caused by: java.security.InvalidKeyException: ECDH key agreement requires ECPublicKey for doPhase
	at org.bouncycastle.jce.provider.asymmetric.ec.KeyAgreement.engineDoPhase(Unknown Source) ~[aadhaar-gateway-1.0.jar:?]

Replacing the bundled library with **bcprov-jdk15on** should solve the problem.

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
