### ISSUE TITLE
AadhaarBridge_2.0.apk not supported Android Marshmallow 6 and Nougat 7 

### ISSUE THREAD

**Issue by hirenpatel868** [khosla-labs/aadhaar-bridge#32]
how to run aadhar sampler app to android latest OS  as AadhaarBridge_2.0.apk not supported Android Marshmallow 6 and Nougat 7 ???

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
