### ISSUE TITLE
e-Kyc Using OTP  for mobile App

### ISSUE THREAD

**Issue by hirenpatel868** [khosla-labs/aadhaar-bridge#33]
we did OTP authentication successfully..but now we want to do **OTP based e-kyc** .so in which we generate OTP successfully but which api we have to call verify otp for ekyc..any **api guide for doing opt based ekyc???**

we have already a licence for both auth + ekyc

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
