### ISSUE TITLE
App not opening after instalation.

### ISSUE THREAD

**Issue by veda2wratha** [khosla-labs/aadhaar-bridge#34]
After installing this apk we are unable to open the app. there is no app in installed list.

**Comment by hirenpatel868** [comment]
To setup Aadhar Bridge Connection for Android APP : 

+ Two App Required

* One is for app gateway which is **Aadhaar Bridge APK v2.0 or v1.5**
This app will be doing PID encryption and will be capturing the raw biometrics in the form of fingerprint and iris once the corresponding intent is called.


* Second one is **Sample app** which is used for 

Testing the aadhar bridge services such as opt kyc or auth

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
