### ISSUE TITLE
Gives 503  response on OTP Request

### ISSUE THREAD

**Issue by amithraj1989** [khosla-labs/aadhaar-bridge#36]
Input: 
{
        "aadhaar-id": "XXXXXXXXXXX",
        "certificate-type": "pre-prod",
        "channel":"SMS",
        "type":"A",
        "location": {
            "type": "",
            "latitude": "",
            "longitude": "",
            "altitude": "",
            "pincode": ""
        }
}
Output: 
{"success":false,"aadhaar-status-code":"503"}.
Tried to contact through Email, Phone no one is responding. Please someone help.

**Comment by hirenpatel868** [comment]
First of all your Gateway server is properly set up or not..?

if setup then confirm that error code 503 coming from Aadhar bridge website not from your local gateway server..

and all is done then sometimes aadhar bridge doents respond for some time you have to wait for response.

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
