### ISSUE TITLE
Status message giving while generating OTP.

### ISSUE THREAD

**Issue by SujeetKr9** [khosla-labs/aadhaar-bridge#37]
**Status** 
Kyc Status: fail
Error, code is :404

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
