### ISSUE TITLE
Using aadhaar-bridge libraries in a Ionic / Apache Cordova App

### ISSUE THREAD

**Issue by jadhavajay** [khosla-labs/aadhaar-bridge#38]
Is there a way to use aadhaar-bridge libraries in an existing cross-platform App which is built using Apache Cordova & Ionic Framework? So that one can target multiple platforms?

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
