### ISSUE TITLE
Receiving "Invalid Response From OTP API" error in gateway server

### ISSUE THREAD

**Issue by chainsingh** [khosla-labs/aadhaar-bridge#39]
I am running gateway server and, when I hit for otp generation, I get an error with details copied from aadhaar-gateway.log as:

_26-Feb-2017 16-17-29:099 ERROR com.aadhaarconnect.bridge.aua.delegates.OtpDelegate Invalid Response from OTP API. API Response : {"timestamp":1488125848985,"status":500,"error":"Intern
al Server Error","exception":"com.orientechnologies.orient.core.exception.OLowDiskSpaceException","message":"Error occurred while executing a write operation to database 'dobby_audit' 
due to limited free space on the disk (33 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen
 the database. The minimal required space is 100 MB. Required space is now set to 100MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .","path":"/kua-se
rvice/otp"}
26-Feb-2017 16-17-29:099 ERROR com.aadhaarconnect.bridge.aua.delegates.OtpDelegate Error code: 500
26-Feb-2017 16-17-29:100 ERROR com.aadhaarconnect.bridge.aua.delegates.OtpDelegate Please visit our website's "Doucmentation --> Techincal-FAQ" section for description_

Please let me know if this is not the right place to ask this question, or a solution to the problem.

I am badly stuck at this. Please help me out :)

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
