### ISSUE TITLE
No Fingerprint device connected 

### ISSUE THREAD

**Issue by Ratnesh-K** [khosla-labs/aadhaar-bridge#40]
Hi, 

 I am using aadhar bridge sample app but not able to capture fingerprint its showing "No Fingerprint device connected". I am using Safran Morpho Device please help me.

 Thanks in advance.

**Comment by hirenpatel868** [comment]
have you installed aadharbridge gateway  apk

**Comment by Ratnesh-K** [comment]
i have installed AadhaarBridge_2.1.apk

**Comment by Ratnesh-K** [comment]
I have installed AadhaarBridge_2.1.apk

**Comment by hirenpatel868** [comment]
Describe issue in details with your setup app n device

**Comment by Ratnesh-K** [comment]
i have installed first AadhaarBridge_2.1.apk then i have installed sample app on device android 4.4.2 Samsung device.

**Comment by hirenpatel868** [comment]
if you are connecting fingerprint device with OTG cable then try to check OTG is working or not becasue in my case i tried 2 or more otg

**Comment by Ratnesh-K** [comment]
I have checked fingerprint device with OTG cable its working fine.
i am using this device [link](http://www.amazon.in/Morpho-MSO-1300-E2-Bio-metric-Fingerprint-Identifications/dp/B01MY159VV?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=8ca7f3b6-2106-432f-bf9f-3252eb450918)

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).

**Comment by VivekPowar** [comment]
is there any source code to read fingerprint from SAFRAN Morpho MSO 1300 E3 2M Model
