### ISSUE TITLE
Http error code 405 with sample app and gateway code

### ISSUE THREAD

**Issue by asmsuchi** [khosla-labs/aadhaar-bridge#6]
Followed the steps to install AadharBridgeSampler app and the gateway code and am seeing the following error on the device log

03-03 15:46:37.142 12967-13958/com.aadhaarconnect.bridge.sampler D/AadhaarAuthAsyncTask: URI : http://<HOST>:<CUSTOM_PORT_NUMBER>/hackgate/hackathon/auth
03-03 15:46:37.270 12967-12967/com.aadhaarconnect.bridge.sampler I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@297ad467 time:15417269
03-03 15:46:38.438 12967-13958/com.aadhaarconnect.bridge.sampler D/AadhaarAuthAsyncTask: RESPONSE CODE : 405

SETUP
----------
(1) Unzipped and setup the gateway server with the following application.properties
--------START application.properties--------------------------------
keystore.location=<P12_LOCATION>
keystore.pass=<PASSWORD>
keystore.alias=<ALIAS>
x09cert.location=<CER_LOCATION>
aua.host.auth.url=https://bridge.aadhaarconnect.com/aua/auth
aua.host.bfd.url=https://bridge.aadhaarconnect.com/aua/bfd
aua.host.otp.url=https://bridge.aadhaarconnect.com/aua/otp
aua.host.kyc.url=https://bridge.aadhaarconnect.com/aua/kyc
subaua.code=<SUBAUA_CODE>
timeout.in.sec=300000
server.port=<CUSTOM_PORT_NUMBER>
-----------------END application.properties--------------------

(2) Changed serverHost to http://<HOST_NAME>:<CUSTOM_PORT_NUMBER> via AadharBridgeSamplerApp.

Can you please let me know how to fix this issue?

**Comment by asmsuchi** [comment]
The URL used above is http://<HOST>:<CUSTOM_PORT_NUMBER>/hackgate/hackathon/auth which resulted in a 405 response code

URL http://<HOST>:<CUSTOM_PORT_NUMBER>/auth results in a 500 response code.

**Comment by smutneja26** [comment]
Kindly specify the URL of the machine(along with the port) on which your gateway jar is running. The request needs to be sent to the gateway which will do the PID encryption and XML formation and will thereafter forward it to the Aadhaar Bridge Server.

**Comment by smutneja03** [comment]
Kindly specify the URL of the machine(along with the port) on which your gateway jar is running. The request needs to be sent to the gateway which will do the PID encryption and XML formation and will thereafter forward it to the Aadhaar Bridge Server.

**Comment by asmsuchi** [comment]
http://ec2-52-34-232-213.us-west-2.compute.amazonaws.com:9000
<http://ec2-52-34-232-213.us-west-2.compute.amazonaws.com:9000/auth>

<http://ec2-52-34-232-213.us-west-2.compute.amazonaws.com:9000/auth>
I <http://ec2-52-34-232-213.us-west-2.compute.amazonaws.com:9000/auth> did
not want to add this info in github. So please do not mention this host
name in the issue.
Suchi

**Comment by smutneja26** [comment]
The request for the Aadhaar Bridge Service needs to be generated from a server which is located in India. The same has been mentioned in the Sub AUA agreement as well.

In order to test the system, you can try deploying the gateway on your local machine first and then test the application.

**Comment by SuryaVenkat** [comment]
Hi, even i am also getting 500 response code while otp api is hitted, plz suggest and guide me..

**Comment by dhanushkumarv** [comment]
hi,
while running the json script i am getting following error.

{
  "code": 500,
  "message": "java.security.cert.CertificateException: java.lang.IllegalArgumentException: unknown object in factory: org.bouncycastle.asn1.DERInteger",
  "detail": "com.aadhaarconnect.bridge.security.XMLSigner.getPublicKey(XMLSigner.java:190)\ncom.aadhaarconnect.bridge.security.XMLSigner.signXML(XMLSigner.java:107)\ncom.aadhaarconnect.bridge.aua.delegates.AbstractDelegate.sign(AbstractDelegate.java:164)\ncom.aadhaarconnect.bridge.aua.delegates.OtpDelegate.signXml(OtpDelegate.java:119)\ncom.aadhaarconnect.bridge.gate.GatewayController.otp(GatewayController.java:109)\n"
}
