### ISSUE TITLE
Internal System Error for unknown reason

### ISSUE THREAD

**Issue by better-place** [khosla-labs/aadhaar-bridge#8]
Hi Team,

We are facing "Internal System Error for unknown reason" while doing Ekyc. This is not always some time we are getting this error. We are also not able to see the kyc logs on the aadhaar bridge portal that also giving internal_error. Please help us to understand the problem.

**Comment by better-place** [comment]
Hi Team,

Any update on this? We are already live and our clients are facing this issue. Expecting quick response please

**Comment by smutneja26** [comment]
As the request from Aadhaar bridge gets forwarded to the ASA's, there might be some instances wherein the selected ASA is not able to reach to the UIDAI or get a valid response from the UIDAI, due to which you might get an error at your end.

**Comment by better-place** [comment]
How to avoid this error?

**Comment by smutneja26** [comment]
As this is something that is managed by the ASA's, it will be tough for us to comment on that. We try our best to ensure our connectivity is to the best with them, which is something in our control.

**Comment by better-place** [comment]
It's too much please check our log. For all request we have to try 2-3 times for successful response. This is not acceptable that there are some connectivity issue. We need solution for this.

**Comment by smutneja26** [comment]
On checking the logs, the error that its showing is E-119. You can refer the link http://cca.gov.in/cca/sites/default/files/files/eSign-APIv1.0-DocVersion1.5-24.02.2015%20.pdf in order to map the description of the same. 

**ASA/KSA is unable to connect to UIDAI server** is what it says.

**Comment by better-place** [comment]
Then please follow up with ASA and let them know the issue.

Thanks & Regards,
*Pulkit Gupta*
Chief Technical Officer
*BetterPlace Safety Solutions Pvt. Ltd.*
144,144/1, 5th Floor
Shubharam Complex,
M.G. Road, Bengaluru – 560001
Karnataka, India
Mobile: +91 9886655380
www.vishwasofindia.com
