### ISSUE TITLE
Log time not having day night information

### ISSUE THREAD

**Issue by better-place** [khosla-labs/aadhaar-bridge#9]
Hi Team,

I will be good you provide logs on portal with AM-PM or make it in 24-hours format. By seeing not clear weather it day or night.

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
